services:
  robot:
    image: test:1.0.0
    build: .
    container_name: robot

  # For M1, M2, M3
  hub:
    image: seleniarm/hub
    ports:
      - 4444:4444
  chrome:
    image: seleniarm/node-chromium
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  # For Linux/ Windows + AMD 64
  # hub:
  #   image: selenium/hub:4.22.0-20240621
  #   container_name: selenium-hub
  #   ports:
  #     - "4442:4442"
  #     - "4443:4443"
  #     - "4444:4444"
  # chrome:
  #   image: selenium/node-chrome:4.22.0-20240621
  #   shm_size: 2gb
  #   depends_on:
  #     - hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443